/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'banner-images': BannerImage;
    activiteiten: Activiteiten;
    leiders: Leider;
    'leiders-foto': LeidersFoto;
    'random-afbeeldingen': RandomAfbeeldingen;
    'homepage-hero-images': HomepageHeroImage;
    'homepage-heros': HomepageHero;
    events: Event;
    weekends: Weekend;
    camps: Camp;
    enrollments: Enrollment;
    photoAlbums: PhotoAlbum;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'banner-images': BannerImagesSelect<false> | BannerImagesSelect<true>;
    activiteiten: ActiviteitenSelect<false> | ActiviteitenSelect<true>;
    leiders: LeidersSelect<false> | LeidersSelect<true>;
    'leiders-foto': LeidersFotoSelect<false> | LeidersFotoSelect<true>;
    'random-afbeeldingen': RandomAfbeeldingenSelect<false> | RandomAfbeeldingenSelect<true>;
    'homepage-hero-images': HomepageHeroImagesSelect<false> | HomepageHeroImagesSelect<true>;
    'homepage-heros': HomepageHerosSelect<false> | HomepageHerosSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    weekends: WeekendsSelect<false> | WeekendsSelect<true>;
    camps: CampsSelect<false> | CampsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    photoAlbums: PhotoAlbumsSelect<false> | PhotoAlbumsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    infoPage: InfoPage;
    inschrijvenPage: InschrijvenPage;
  };
  globalsSelect: {
    infoPage: InfoPageSelect<false> | InfoPageSelect<true>;
    inschrijvenPage: InschrijvenPageSelect<false> | InschrijvenPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijving van de afbeelding voor toegankelijkheid
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Banner afbeeldingen voor weekends en kampen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner-images".
 */
export interface BannerImage {
  id: number;
  /**
   * Geef de banner een duidelijke naam (bv. "Zomerkamp Bos", "Winterkamp Bergen")
   */
  name: string;
  /**
   * Beschrijving van de afbeelding voor toegankelijkheid (automatisch ingevuld indien leeg)
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activiteiten".
 */
export interface Activiteiten {
  id: number;
  title: string;
  division: ('kapoenen' | 'wouters' | 'jonggivers' | 'givers' | 'jin')[];
  startDate: string;
  endDate: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Beheer inschrijvingen voor deze activiteit
   */
  enrollmentSettings?: {
    /**
     * Schakel dit in om inschrijvingen toe te staan voor deze activiteit
     */
    enabled?: boolean | null;
    /**
     * Sluit de inschrijvingen handmatig (toont aangepast bericht)
     */
    closed?: boolean | null;
    /**
     * Verberg de inschrijfknop op de website zonder inschrijvingen te sluiten
     */
    hideButton?: boolean | null;
    /**
     * Dit bericht wordt getoond wanneer inschrijvingen gesloten zijn
     */
    closedMessage?: string | null;
    enrollmentLink?: string | null;
    /**
     * Upload een PDF document met extra informatie over de activiteit
     */
    infoDocument?: (number | null) | Media;
    /**
     * Voeg extra tekstvragen toe aan het inschrijfformulier
     */
    customQuestions?:
      | {
          /**
           * Bijvoorbeeld: "Heeft uw kind allergieën?"
           */
          question: string;
          /**
           * Is deze vraag verplicht om in te vullen?
           */
          required?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Na deze datum zijn geen inschrijvingen meer mogelijk
     */
    enrollmentDeadline?: string | null;
    /**
     * Dit bericht wordt getoond nadat het formulier is verstuurd
     */
    customMessage?: string | null;
    /**
     * Is dit een betalende activiteit?
     */
    isPaid?: boolean | null;
    /**
     * Prijs in euro per kind
     */
    pricePerChild?: number | null;
    /**
     * Instructies voor betaling (bijv. rekeningnummer, mededeling)
     */
    paymentInstructions?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leiders".
 */
export interface Leider {
  id: number;
  name: string;
  takken: ('kapoenen' | 'wouters' | 'jonggivers' | 'givers' | 'jin' | 'groepsleiding' | 'gestopt')[];
  /**
   * Als het 1e leidingsjaar bvb 2024-2025, vul dan 2024 in
   */
  year: number;
  /**
   * Vul hier het eerste jaar in waarin de leider stopt (bv. 2024).
   */
  stopYear?: number | null;
  totem?: string | null;
  totemBeschrijving?: string | null;
  description?: string | null;
  image?: (number | null) | LeidersFoto;
  phoneNumber: string;
  email: string;
  kapoenenNaam?: string | null;
  wouterNaam?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leiders-foto".
 */
export interface LeidersFoto {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "random-afbeeldingen".
 */
export interface RandomAfbeeldingen {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero-images".
 */
export interface HomepageHeroImage {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-heros".
 */
export interface HomepageHero {
  id: number;
  name: string;
  /**
   * Used for ordering/priority (lower numbers appear first)
   */
  presence: number;
  homeHeroImage: number | HomepageHeroImage;
  /**
   * If one of Title, Description, or Button is filled in, all must be filled in
   */
  title?: string | null;
  /**
   * If one of Title, Description, or Button is filled in, all must be filled in
   */
  description?: string | null;
  /**
   * If one of Title, Description, or Button is filled in, all must be filled in
   */
  button?: {
    text?: string | null;
    /**
     * URL where the button should link to
     */
    link?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startDate: string;
  endDate?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Bijvoorbeeld: "Inschrijven", "Meer info", "Aanmelden"
   */
  buttonText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekends".
 */
export interface Weekend {
  id: number;
  title: string;
  division: ('kapoenen' | 'wouters' | 'jonggivers' | 'givers' | 'jin')[];
  startDate: string;
  endDate: string;
  /**
   * Kies een banner afbeelding voor dit weekend uit de banner collectie
   */
  bannerImage?: (number | null) | BannerImage;
  /**
   * Beheer inschrijvingen voor dit weekend
   */
  enrollmentSettings?: {
    /**
     * Schakel dit in om inschrijvingen toe te staan voor dit weekend
     */
    enabled?: boolean | null;
    /**
     * Sluit de inschrijvingen handmatig (toont aangepast bericht)
     */
    closed?: boolean | null;
    /**
     * Verberg de inschrijfknop op de website zonder inschrijvingen te sluiten
     */
    hideButton?: boolean | null;
    /**
     * Dit bericht wordt getoond wanneer inschrijvingen gesloten zijn
     */
    closedMessage?: string | null;
    enrollmentLink?: string | null;
    /**
     * Upload een PDF document met extra informatie over het weekend
     */
    infoDocument?: (number | null) | Media;
    /**
     * Voeg extra tekstvragen toe aan het inschrijfformulier
     */
    customQuestions?:
      | {
          /**
           * Bijvoorbeeld: "Heeft uw kind allergieën?"
           */
          question: string;
          /**
           * Is deze vraag verplicht om in te vullen?
           */
          required?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Na deze datum zijn geen inschrijvingen meer mogelijk
     */
    enrollmentDeadline?: string | null;
    /**
     * Dit bericht wordt getoond nadat het formulier is verstuurd
     */
    customMessage?: string | null;
    /**
     * Is dit een betalend weekend?
     */
    isPaid?: boolean | null;
    /**
     * Prijs in euro per kind
     */
    pricePerChild?: number | null;
    /**
     * Instructies voor betaling (bijv. rekeningnummer, mededeling)
     */
    paymentInstructions?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "camps".
 */
export interface Camp {
  id: number;
  title: string;
  division: ('kapoenen' | 'wouters' | 'jonggivers' | 'givers' | 'jin')[];
  startDate: string;
  endDate: string;
  /**
   * Kies een banner afbeelding voor dit kamp uit de banner collectie
   */
  bannerImage?: (number | null) | BannerImage;
  /**
   * Beheer inschrijvingen voor dit kamp
   */
  enrollmentSettings?: {
    /**
     * Schakel dit in om inschrijvingen toe te staan voor dit kamp
     */
    enabled?: boolean | null;
    /**
     * Sluit de inschrijvingen handmatig (toont aangepast bericht)
     */
    closed?: boolean | null;
    /**
     * Verberg de inschrijfknop op de website zonder inschrijvingen te sluiten
     */
    hideButton?: boolean | null;
    /**
     * Dit bericht wordt getoond wanneer inschrijvingen gesloten zijn
     */
    closedMessage?: string | null;
    enrollmentLink?: string | null;
    /**
     * Upload een PDF document met extra informatie over het kamp
     */
    infoDocument?: (number | null) | Media;
    /**
     * Voeg extra tekstvragen toe aan het inschrijfformulier
     */
    customQuestions?:
      | {
          /**
           * Bijvoorbeeld: "Heeft uw kind allergieën?"
           */
          question: string;
          /**
           * Is deze vraag verplicht om in te vullen?
           */
          required?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Na deze datum zijn geen inschrijvingen meer mogelijk
     */
    enrollmentDeadline?: string | null;
    /**
     * Dit bericht wordt getoond nadat het formulier is verstuurd
     */
    customMessage?: string | null;
    /**
     * Is dit een betalend kamp?
     */
    isPaid?: boolean | null;
    /**
     * Prijs in euro per kind
     */
    pricePerChild?: number | null;
    /**
     * Instructies voor betaling (bijv. rekeningnummer, mededeling)
     */
    paymentInstructions?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Inschrijvingen voor activiteiten, weekends en kampen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  /**
   * Automatisch ingevuld uit contact informatie
   */
  participantEmail?: string | null;
  targetType: 'activiteiten' | 'weekends' | 'camps';
  targetId: string;
  /**
   * Titel van de activiteit/weekend/kamp
   */
  targetTitle?: string | null;
  /**
   * Automatisch berekend
   */
  numberOfChildren?: number | null;
  children: {
    participantInfo: {
      firstName: string;
      lastName: string;
    };
    id?: string | null;
  }[];
  contactInfo: {
    email: string;
  };
  additionalOptions?: {
    /**
     * Extra opmerkingen of vragen
     */
    comments?: string | null;
    /**
     * Antwoorden op extra vragen
     */
    customAnswers?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Totaal te betalen bedrag
   */
  totalPrice?: number | null;
  submittedAt?: string | null;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'paid') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photoAlbums".
 */
export interface PhotoAlbum {
  id: number;
  name: string;
  year: number;
  tak: 'kapoenen' | 'wouters' | 'jonggivers' | 'givers' | 'jin' | 'groepsactiviteit';
  link: string;
  /**
   * Optioneel: waar is dit album genomen?
   */
  location?: string | null;
  /**
   * Beste is een groepsfoto in landscape formaat
   */
  coverImage: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'banner-images';
        value: number | BannerImage;
      } | null)
    | ({
        relationTo: 'activiteiten';
        value: number | Activiteiten;
      } | null)
    | ({
        relationTo: 'leiders';
        value: number | Leider;
      } | null)
    | ({
        relationTo: 'leiders-foto';
        value: number | LeidersFoto;
      } | null)
    | ({
        relationTo: 'random-afbeeldingen';
        value: number | RandomAfbeeldingen;
      } | null)
    | ({
        relationTo: 'homepage-hero-images';
        value: number | HomepageHeroImage;
      } | null)
    | ({
        relationTo: 'homepage-heros';
        value: number | HomepageHero;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'weekends';
        value: number | Weekend;
      } | null)
    | ({
        relationTo: 'camps';
        value: number | Camp;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'photoAlbums';
        value: number | PhotoAlbum;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner-images_select".
 */
export interface BannerImagesSelect<T extends boolean = true> {
  name?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activiteiten_select".
 */
export interface ActiviteitenSelect<T extends boolean = true> {
  title?: T;
  division?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  enrollmentSettings?:
    | T
    | {
        enabled?: T;
        closed?: T;
        hideButton?: T;
        closedMessage?: T;
        enrollmentLink?: T;
        infoDocument?: T;
        customQuestions?:
          | T
          | {
              question?: T;
              required?: T;
              id?: T;
            };
        enrollmentDeadline?: T;
        customMessage?: T;
        isPaid?: T;
        pricePerChild?: T;
        paymentInstructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leiders_select".
 */
export interface LeidersSelect<T extends boolean = true> {
  name?: T;
  takken?: T;
  year?: T;
  stopYear?: T;
  totem?: T;
  totemBeschrijving?: T;
  description?: T;
  image?: T;
  phoneNumber?: T;
  email?: T;
  kapoenenNaam?: T;
  wouterNaam?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leiders-foto_select".
 */
export interface LeidersFotoSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "random-afbeeldingen_select".
 */
export interface RandomAfbeeldingenSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero-images_select".
 */
export interface HomepageHeroImagesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-heros_select".
 */
export interface HomepageHerosSelect<T extends boolean = true> {
  name?: T;
  presence?: T;
  homeHeroImage?: T;
  title?: T;
  description?: T;
  button?:
    | T
    | {
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  buttonText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekends_select".
 */
export interface WeekendsSelect<T extends boolean = true> {
  title?: T;
  division?: T;
  startDate?: T;
  endDate?: T;
  bannerImage?: T;
  enrollmentSettings?:
    | T
    | {
        enabled?: T;
        closed?: T;
        hideButton?: T;
        closedMessage?: T;
        enrollmentLink?: T;
        infoDocument?: T;
        customQuestions?:
          | T
          | {
              question?: T;
              required?: T;
              id?: T;
            };
        enrollmentDeadline?: T;
        customMessage?: T;
        isPaid?: T;
        pricePerChild?: T;
        paymentInstructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "camps_select".
 */
export interface CampsSelect<T extends boolean = true> {
  title?: T;
  division?: T;
  startDate?: T;
  endDate?: T;
  bannerImage?: T;
  enrollmentSettings?:
    | T
    | {
        enabled?: T;
        closed?: T;
        hideButton?: T;
        closedMessage?: T;
        enrollmentLink?: T;
        infoDocument?: T;
        customQuestions?:
          | T
          | {
              question?: T;
              required?: T;
              id?: T;
            };
        enrollmentDeadline?: T;
        customMessage?: T;
        isPaid?: T;
        pricePerChild?: T;
        paymentInstructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  participantEmail?: T;
  targetType?: T;
  targetId?: T;
  targetTitle?: T;
  numberOfChildren?: T;
  children?:
    | T
    | {
        participantInfo?:
          | T
          | {
              firstName?: T;
              lastName?: T;
            };
        id?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
      };
  additionalOptions?:
    | T
    | {
        comments?: T;
        customAnswers?: T;
      };
  totalPrice?: T;
  submittedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photoAlbums_select".
 */
export interface PhotoAlbumsSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  tak?: T;
  link?: T;
  location?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infoPage".
 */
export interface InfoPage {
  id: number;
  title: string;
  intro: string;
  pillars?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  heroImage: number | RandomAfbeeldingen;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inschrijvenPage".
 */
export interface InschrijvenPage {
  id: number;
  title: string;
  subtitle: string;
  ctaButtonText: string;
  ctaButtonUrl: string;
  ctaSubtext?: string | null;
  whyJoinTitle?: string | null;
  whyJoinReasons?:
    | {
        icon: 'users' | 'star' | 'heart' | 'mapPin' | 'calendar' | 'sparkles';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  existingMembersSection?: {
    title?: string | null;
    content?: string | null;
    infoBoxTitle?: string | null;
    infoBoxContent?: string | null;
  };
  divisionsTitle?: string | null;
  divisionsSubtitle?: string | null;
  practicalInfoTitle?: string | null;
  practicalInfo?:
    | {
        icon?: ('calendar' | 'mapPin' | 'euro' | 'shirt') | null;
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  finalCtaSection?: {
    title?: string | null;
    content?: string | null;
    buttonText?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infoPage_select".
 */
export interface InfoPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  pillars?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  heroImage?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inschrijvenPage_select".
 */
export interface InschrijvenPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaButtonText?: T;
  ctaButtonUrl?: T;
  ctaSubtext?: T;
  whyJoinTitle?: T;
  whyJoinReasons?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  existingMembersSection?:
    | T
    | {
        title?: T;
        content?: T;
        infoBoxTitle?: T;
        infoBoxContent?: T;
      };
  divisionsTitle?: T;
  divisionsSubtitle?: T;
  practicalInfoTitle?: T;
  practicalInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        content?: T;
        id?: T;
      };
  finalCtaSection?:
    | T
    | {
        title?: T;
        content?: T;
        buttonText?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}