services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/media:/usr/src/app/media
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/media-leiding
    env_file:
      - .env
    entrypoint: []  # Override the entrypoint
    command: ["npm", "run", "dev"]
    depends_on:
      - db  # Ensures the database is ready before starting

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payload
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  data:
  pgdata: