services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - ./frontend/media:/app/media
      - /app/.next
    env_file:
      - .env
    command: pnpm run dev
    depends_on:
      - db  # Ensures the database is ready before starting

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payload
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  data:
  node_modules:
  pgdata: